# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7108dbf290cd4fe4ea9cc349b389e6d504a8f7681e5416c95440cc744f746e968c276250755c3a81274510871f096eaf10b9a91d50a3aa0a04501ea130cddfc

test:
  secret_key_base: c2de02c31c1392ff5088b5961f853102cb7abbccc23ba3f339546a7ee9c1c7d3c09b9954ba68adfffb2c4378dda6708906138575c5c3a78fd3eba8de2b5abd2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
